var firstName = "Abhijeetsingh"; 
console.log(firstName);
var fullName = "Abhijeetsingh Ajitsingh Rajput";
console.log(fullName);
var myLove = "I Love Only JS";
console.log(myLove);
var firstName = "Abhijeetsingh";
console.log(firstName);
var lastName = "Rajput";
console.log(lastName);
var age = "24years";
console.log(age);
var address = "a/p Datala Tal:- Malkapur Dist:- Buldhana";
console.log(address);
var pincode = "443102";
console.log(pincode);
var gender = "Male";
console.log(gender);
var married = "NO";
console.log(married);
